#! /bin/bash

set $mainText #28282b
set $inacText #F6F7F9
set $inficator #32302f

set $main #B192A1
set $inactive #28282b


# class                 border     backgr.     text       indicator     child_border
client.focused          $main      $main       $mainText  $main         $main
client.unfocused        $inactive  $inactive   $inacText  $inactive     $inactive
client.focused_inactive $inactive  $inactive   $inacText  $inactive     $inactive