#! /bin/bash

set $mainText #eeeeee
set $inacText #eeeeee
set $inficator #16161C

set $main #df98ca
set $inactive #a59d98


# class                 border     backgr.     text       indicator     child_border
client.focused          $main      $main       $mainText  $main         $main
client.unfocused        $inactive  $inactive   $inacText  $inactive     $inactive
client.focused_inactive $inactive  $inactive   $inacText  $inactive     $inactive
